version: "2"

networks:
  eticket_net:
    external: true

services:
  eticket_backend_waiting:
    env_file:
      - ../env/eticket-dev-datasource.env
    build: ../../workspace/backend-waiting/Dockerfile/
    container_name: eticket_backend_waiting
    image: eticket/backend-waiting
    restart: on-failure
    networks:
      - eticket_net
    ports:
      - 31880:8080
