version: "2"

networks:
  eticket_net:
    external: true

services:
  eticket_backend:
    env_file:
      - ../env/eticket-dev-datasource.env
    build: ../../workspace/backend/Dockerfile/
    container_name: eticket_backend
    image: eticket/backend
    restart: on-failure
    ports:
      - 38080:8080
    networks:
      - eticket_net
