spring:
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33066/eticket
    username: root
    password: hello_eticket
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  main:
    allow-circular-references: true

eticket:
  redis:
    auth:
      host: localhost
      port: 36379
      database: 1
    reservation:
      host: localhost
      port : 36379
      database: 2
    ticketing:
      host: localhost
      port: 36379
      database: 3
  auth:
    jwt:
      insecure: true
      insecure-key-path: insecure-rsa-key.pem
      issuer: eticket.org
      access-token-lifetime: 3600
      refresh-token-lifetime: 345600
    challenge:
      lifetime: 180